// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import (
	"github.com/google/uuid"
)

type Todo struct {
	ID     uuid.UUID
	Title  string
	Status string
	UserID uuid.UUID
}

type User struct {
	ID     uuid.UUID
	Name   string
	ApiKey string
}
