// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: todos.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (id, title, status, user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, title, status, user_id
`

type CreateTodoParams struct {
	ID     uuid.UUID
	Title  string
	Status string
	UserID uuid.UUID
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo,
		arg.ID,
		arg.Title,
		arg.Status,
		arg.UserID,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.UserID,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos WHERE id = $1
`

func (q *Queries) DeleteTodo(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTodo, id)
	return err
}

const getTodo = `-- name: GetTodo :one
SELECT id, title, status, user_id FROM todos WHERE id = $1
`

func (q *Queries) GetTodo(ctx context.Context, id uuid.UUID) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodo, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.UserID,
	)
	return i, err
}

const getTodosList = `-- name: GetTodosList :many
SELECT id, title, status, user_id FROM todos
`

func (q *Queries) GetTodosList(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getTodosList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos
SET title = $2, status = $3
WHERE id = $1
RETURNING id, title, status, user_id
`

type UpdateTodoParams struct {
	ID     uuid.UUID
	Title  string
	Status string
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, updateTodo, arg.ID, arg.Title, arg.Status)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.UserID,
	)
	return i, err
}
